### ISSUE TITLE
HTML/CSS issues

### ISSUE THREAD

**Issue by wrdana** [nathalie1226/quizz#2]
- You have all sorts of problems with labels and input fields - please go over the for="" values.
- Run your code in the [HTML validator](https://validator.w3.org/), there are a bunch of errors here
- Make sure your HTML code is indented properly
- Your CSS is too basic. The webpage needs to look better (though that wasn't the focus here..)
- The result appears in the middle of the page - It looks odd. Remove the questions/think of a better place to put the answer in.
- The title shouldn't be empty
  `<title>Title</title>`

**Comment by wrdana** [comment]
You didn't update the code - why did you close the issue?

**Comment by nathalie1226** [comment]
i just did

**Comment by wrdana** [comment]
Not sure you understood what I meant regarding labels and input fields - every input field should have a title.

**Comment by nathalie1226** [comment]
i did it just know put can you please explain to me why title are important?

**Comment by wrdana** [comment]
It looks unprofessional when you have a generic title or no title at all..

**Comment by nathalie1226** [comment]
oki doki
so always put a title on all times of input

**Comment by wrdana** [comment]
Don't confuse title with label - a title goes in the head, a label is per input field.
